import axios, { AxiosResponse } from "axios";
import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import { AxiosErrorData } from "../hooks/useRequest";
import styles from "../styles/Home.module.css";

interface Props {
  data: AxiosResponse | AxiosErrorData;
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Landing Page</h1>
      </main>
    </div>
  );
};

Home.getInitialProps = async () => {
  try {
    const response = await axios.get("/api/users/currentUser");
    return response.data;
  } catch (error) {
    return error as AxiosErrorData;
  }
};

export default Home;
