import { AxiosRequestConfig, AxiosResponse } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { AxiosErrorData } from "../hooks/useRequest";
import styles from "../styles/Home.module.css";
import { axiosInstance } from "../utils/axios";

interface Props {
  data: AxiosResponse | AxiosErrorData;
  currentUser: any;
}

const Home: NextPage<Props> = ({ currentUser }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>{currentUser ? <h1>You are signed In </h1> : <h1>You are not signed in</h1>}</main>
    </div>
  );
};

export default Home;
